package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Apr 26 17:12:03 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Apr 26 17:12:03 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Apr 26 17:12:03 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Apr 26 17:12:03 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Apr 26 17:12:03 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Apr 26 17:12:03 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     *  根据账户和密码取查询用户
     * @param map
     * @return
     */
    User selectUserByLoginActAndPwd( Map<String,Object> map);

    /**
     *  查询所有的用户  不需要参数
     * @return
     */
    List<User> selectAllUsers();

}